name: clisops
channels:
 - conda-forge
 - defaults
dependencies:
 - python >=3.8
 - pip
 - bottleneck>=1.3.1
 - cf_xarray>=0.7.0
 - cftime>=1.4.1
 - dask>=2.6.0
 - gdal
 - geopandas>=0.7
 - loguru>=0.5.3
 - netCDF4>=1.4
 - numba  # needed for xesmf v0.6.3, see: https://github.com/conda-forge/xesmf-feedstock/pull/24
 - numpy>=1.16
 - packaging
 - pandas>=1.0.3
 - poppler>=0.67
 - pyproj>=2.5
 - pooch
 - requests>=2.0
 - roocs-utils>=0.6.4,<0.7
 - shapely>=1.6
 - sparse>=0.8.0  # needed for xesmf v0.6.3, see: https://github.com/conda-forge/xesmf-feedstock/pull/24
 - xarray>=0.15
 - xesmf>=0.6.2
