name: clisops
channels:
 - conda-forge
 - defaults
dependencies:
 - pip
 - numpy>=1.16
 - xarray>=0.15
 - pandas>=1.0.3
 - cftime>=1.4.1
 - netCDF4>=1.4
 - poppler>=0.67
 - shapely>=1.6
 - geopandas>=0.7
 - xesmf>=0.5.2
 - dask>=2.6.0
 - bottleneck>=1.3.1,<1.4
 - pyproj>=2.5
 - requests>=2.0
 #- roocs-utils>=0.2.1
 - cf_xarray>=0.3.1
 - pip:
    - roocs-utils @ git+https://github.com/roocs/roocs-utils.git@master#egg=roocs-utils
