name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-env: [black]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install tox
        run: pip install "tox~=3.0"
      - name: Run linting suite
        run: tox -e ${{ matrix.tox-env }}

  pypi:
    needs: black
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            tox-env: py38
            allowed_to_fail: false
          - python-version: "3.9"
            tox-env: py39
            allowed_to_fail: false
          - python-version: "3.10"
            tox-env: py310
            allowed_to_fail: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: pip install "tox~=3.0"
    - name: Test with tox
      run: tox -e ${{ matrix.tox-env }}
      continue-on-error: ${{ matrix.allowed_to_fail }}

  conda:
    needs: black
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.9"
            upstream: true
            allowed_to_fail: true
          - python-version: "3.10"
            upstream: false
            allowed_to_fail: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Conda (Micromamba) with Python ${{ matrix.python-version }}
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          environment-file: environment.yml
          extra-specs: |
            python=${{ matrix.python-version }}
      - name: Install mamba
        run: |
            conda install -c conda-forge mamba
      - name: Install CLISOPS
        run: |
            pip install -e ".[dev]"
      - name: Install xarray@main
        if: ${{ matrix.upstream }}
        run: |
            pip install git+https://github.com/pydata/xarray.git@main#egg=xarray
      - name: Test with conda
        run: |
            pytest --cov tests
        continue-on-error:  ${{ matrix.allowed_to_fail }}
